### ISSUE TITLE
About the weights of LDM-4

### ISSUE THREAD

**Issue by TaylorJocelyn** [ThisisBillhe/PTQD#15]
May I ask if you trained the weight file of LDM-4 yourself? I only found the weight of LDM-8 in the late diffusion project, as shown in the following figure，
![55eac0097604fa71434c7fdaaa63385f](https://github.com/ziplab/PTQD/assets/60263416/88f1c900-87f8-42d0-9271-bb6cc548d70d)
Looking forward to your answer very much.

**Comment by ThisisBillhe** [comment]
Hi, You can download the model checkpoint from [here](https://github.com/CompVis/latent-diffusion/blob/main/scripts/latent_imagenet_diffusion.ipynb)

**Comment by TaylorJocelyn** [comment]
Finally found it, thank you very much！
