### ISSUE TITLE
No Input data is collected

### ISSUE THREAD

**Issue by junhyukso** [ThisisBillhe/PTQD#2]
Hi I'm trying to reproduce your results based on your code.  
However, `globalcar.getInputList()` returns empty list. It seems that there are no logic about saving input in `DDIMSampler.sample()` 
can you please check it ??

**Comment by ThisisBillhe** [comment]
Hi there. Remember to uncomment line 987-988 in ldm/models/diffusion/ddpm.py, as I wrote at the beginning of quant_scripts/collect_diffusion_input_imagenet.py

**Comment by junhyukso** [comment]
Oh i miss that.
Now it works perfectly. Thank you!

**Comment by digbangbang** [comment]
Hi, I met the same problem when 'python3 quant_scripts/quantize_ldm_brecq.py`
It came out ValueError: num_samples should be a positive integer value, but got num_samples=0

I noted that the collect_diffusion_input_imagenet.py use the DDIMsampler, but the DDPM.py maybe is not used in this project,
so it came the [](torch.load), and uncomment line 987-988 in ldm/models/diffusion/ddpm.py seems didn't work.

So what can I do for this problem?
