### ISSUE TITLE
Quantization specifically for txt2img 

### ISSUE THREAD

**Issue by yueweiyang** [ThisisBillhe/PTQD#3]
Thanks @ThisisBillhe for this amazing quantization work on diffusion model.

Based on the quantization code, it quantizes the model based on collected ImageNet data. So I think the quantization is done in an unconditional way. Do you think if the quantized model is only for txt2img application, collecting prompts data to calibrate could make any difference? In other words, could the conditional quantization work and how different it could be?

Thanks again for the amazing work.

**Comment by ThisisBillhe** [comment]
> Thanks @ThisisBillhe for this amazing quantization work on diffusion model.
> 
> Based on the quantization code, it quantizes the model based on collected ImageNet data. So I think the quantization is done in an unconditional way. Do you think if the quantized model is only for txt2img application, collecting prompts data to calibrate could make any difference? In other words, could the conditional quantization work and how different it could be?
> 
> Thanks again for the amazing work.

 LDM model for ImageNet is a conditional model, which uses class label as conditions. Therefore, we actually collect data in a conditional way. In the case of txt2img, you need to specify (or randomly generate) some prompts for generation data.
