### ISSUE TITLE
Calibrate on whole classes?

### ISSUE THREAD

**Issue by Dixeran** [ThisisBillhe/PTQD#4]
For the need of collecting calibration data over the whole trained classes ([classes = [i for i in range(1000)]](https://github.com/ThisisBillhe/PTQD/blob/84a120a7d0cf37f01ca1843018c8bbb67e432368/quant_scripts/collect_diffusion_input_imagenet.py#L42)) , is this method only viable for self-trained models?

**Comment by ThisisBillhe** [comment]
It is not necessary to collect calibration data over all the class labels.  Using fewer class labels for calibration also works fine.
