### ISSUE TITLE
Could you support stable diffusion v1.5 models？

### ISSUE THREAD

**Issue by felixslu** [ThisisBillhe/PTQD#5]
In the industry，the AIGC models  are all based on stable diffusion v1.5 and above. 
 Are there any future plans to support this aspect?

**Comment by ThisisBillhe** [comment]
Hi, you may implement your own PTQD with SD v1.5.  It won't be that cumbersome since they share the same code structure.

**Comment by ThisisBillhe** [comment]
Hi, you may implement your own PTQD with SD v1.5.  It won't be that cumbersome since they share the same code structure.
